### ISSUE TITLE
Changed API?

### ISSUE THREAD

**Issue by chakkimatti** [theasta/grunt-assets-versioning#67]
I have this in my in my gruntFile.js and it worked fine before updating Node, but now it, not only uses hash instead of date but also skips making assets_versioning.js. Something I'm doing wrong? My apologies in advance if this is not the right place for this.
Here's the part for assets_versioning
		assets_versioning: {
		    options: {
		      use: 'date',
		      dateFormat: 'MMDDHHmm',
		      tasks: ['uglify:min'],
		      skipExisting: false
		    },
		    target: {
		    	expand: true,
		    	options: {
		    		output: 'versioning/assets_versioning.json'
			    	},
		    },
		  }
the minified and versioned file is hashed, not dated and the assets_versioning.js doesn't get created.

Thank you,
Aron (a.k.a. chakkimatti)

**Comment by theasta** [comment]
Yes, the API changed with version v0.6.0. Please read the readme file for more details. If you don't want to upgrade, you can update your package.json file so that it points out to the specific version you want to stick with.

**Comment by chakkimatti** [comment]
Thank you. I will.
